### ISSUE TITLE
Добавить линтер

### ISSUE THREAD

**Issue by tshemsedinov** [kirilinsane/CourseWork#1]
- [x] Добавить eslint и конфигурацию, лучше взять эту: [.eslintrc.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.eslintrc.json)
- [x] Добавить `package.json` с зависимостями, тем же eslint. Пример: [package.json](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/package.json)

**Comment by kirilinsane** [comment]
Done

**Comment by kirilinsane** [comment]
Done
